### ISSUE TITLE
Case insensible compare functions

### ISSUE THREAD

**Issue by emoon** [rampantpixels/foundation_lib#10]
Would be nice to have these in string.c/h as one thing one often runs into to is that stricmp may not exist or is named something different (like strcasecmp) depending on platform.

**Comment by MJansson** [comment]
Sounds reasonable, I will add it

**Comment by emoon** [comment]
Thanks!

**Comment by MJansson** [comment]
Added inital wrappers in feature/strcasecmp branch, named string_equal_nocase and string_equal_substr_nocase. Have not yet gone through all platforms though.

**Comment by emoon** [comment]
Thanks! Sounds good.

**Comment by MJansson** [comment]
merged to develop branch
