### ISSUE TITLE
Support for killing process

### ISSUE THREAD

**Issue by emoon** [rampantpixels/foundation_lib#11]
Hi, 

Sorry to bug you with more feature requests but something that would be very useful is something like

```C
FOUNDATION_API int process_kill( process_t* proc );
```

I'm not sure all platforms you support can use this but for desktop platforms this is quite useful. I have some cases where I spawn a program, run a bunch of tests (connecting with sockets) and the easiest way to shut it down is just to kill the process.

**Comment by MJansson** [comment]
First implementation in feature/process-kill branch, not written tests or tested all platforms yet.

**Comment by MJansson** [comment]
Test added and merged into develop branch.

**Comment by emoon** [comment]
Sweet! Thanks :)

**Comment by joewoy** [comment]
I agree this is great to have right in the lib, thanks!
