### ISSUE TITLE
random32_range(0, 1) doesn't return 1

### ISSUE THREAD

**Issue by etvvwarv** [rampantpixels/foundation_lib#12]
As the title says, it doesn't return most high value.

**Comment by MJansson** [comment]
As designed, docs say "Generate 32 bit random number in [low,high) range" which should be read as low value is included in returned values while high value is excluded.

**Comment by MJansson** [comment]
Reasoning behind this is that a normal use case is to randomize an index into an array. You can then do random32_range(0, size), in which case you don't want to have size as a returned value since that would index outside the array.
