### ISSUE TITLE
build ？

### ISSUE THREAD

**Issue by 1491163117** [rampantpixels/foundation_lib#16]
How to build, can you give a template？thanks

**Comment by MJansson** [comment]
In the build directory you'll find projects for Visual Studio and XCode. Or install ninja, run the configure script and run ninja. Output libfaries will be put in lib, binaries in bin.

**Comment by 1491163117** [comment]
ninja_required_version = 1.3

# configure.py arguments
configure_args = --target=android --host=macosx --toolchain=gcc $
    --config=debug --arch=arm7 --monolithic --coverage

# configure options
configure_target = android
configure_host = macosx
configure_toolchain = gcc
configure_archs = arm7
configure_configs = debug

buildpath = build/ninja/android
target = android
config = 
ndk = /opt/android-ndk-r16
sdk = /opt/android-osx-sdk
sysroot = /opt/android-ndk-r16/sysroot
