### ISSUE TITLE
Lots of errors on Travis for macOS

### ISSUE THREAD

**Issue by pbtrung** [rampantpixels/foundation_lib#19]
Following is the log when I tried to use this lib in one of my projects on Travis for macOS:
https://travis-ci.org/pbtrung/cbup/jobs/343104973
Please scroll to the end.
Thanks.

**Comment by MJansson** [comment]
Probably need to update my apple wrapper header to the latest SDK. Thanks for reporting, will look into it asap.

**Comment by MJansson** [comment]
Now I get "We couldn't find the repository pbtrung/cbup" when trying to access that link.

How are you including the foundation headers in your project? The foundation lib itself and my own projects using it compiles fine with the latest XCode and SDK.

**Comment by pbtrung** [comment]
I accidentally deleted the repo and cannot reproduce the errors anymore. 
Close this for now.
Thanks.

**Comment by MJansson** [comment]
One thing to keep in mind is that when building with XCode, you might have to disable use of header maps and disable C/Obj-C modules, since this could cause Apple headers to be included in bulk before foundation lib headers, causing error like these.
