### ISSUE TITLE
Consider remove PNaCl support

### ISSUE THREAD

**Issue by pbtrung** [rampantpixels/foundation_lib#22]
As shown in [Goodbye PNaCl, Hello WebAssembly!](https://blog.chromium.org/2017/05/goodbye-pnacl-hello-webassembly.html), PNaCl is being deprecated. Removing it would reduce your maintenance burden unless you are using it in other projects. The latest Chromium (64.0.3282.186) cannot run the PNaCl test suite anymore.
Thanks.

**Comment by MJansson** [comment]
Removed

**Comment by pbtrung** [comment]
There are still a lot of `PNaCl` in `README.md`

**Comment by MJansson** [comment]
Done

**Comment by pbtrung** [comment]
I do appreciate your hard work. But it's my OCD to tell you that there is still one `PNaCl` in `README.md`.
Thanks.

**Comment by MJansson** [comment]
Hopefully all cleaned now :)

**Comment by pbtrung** [comment]
Seems clean :)
