### ISSUE TITLE
Why this library? Why C for game?

### ISSUE THREAD

**Issue by pbtrung** [rampantpixels/foundation_lib#23]
I do like C but I am not in the game industry, so I would like to ask for your opinions on why you created this library and why you use C for game development (I suppose) vs C++?

**Comment by MJansson** [comment]
I've been programming in C++ for a long time (20+ years now), but as I am now an old grumpy fart I find myself liking the directness of C more and more, and the obsfucated way of modern C++ less.

When I made [Rampant Kittens](http://www.rampantpixels.com) in C + Lua I decided to generalize the code base into this foundation library along with some other modules that is slowly turning into a game framework that I will eventually release to the public domain.

**Comment by pbtrung** [comment]
Exactly what I like about C and why I am trying to avoid C++.
Well, thanks for your reply.
