### ISSUE TITLE
Maybe a bug in POSIX fs_is_file

### ISSUE THREAD

**Issue by pbtrung** [rampantpixels/foundation_lib#24]
`bool fs_is_file(const char* path, size_t length)`
On Arch Linux if `path` does not exist, returned value is random.
Solution:
```
int rc = stat(finalpath.str, &st);
if (rc == 0 && (st.st_mode & S_IFREG))
    return true;
```

**Comment by MJansson** [comment]
Added stat return value checks and unified the file/dir checks in 052e7e015

**Comment by pbtrung** [comment]
Looks good now.
Thanks.
